### ISSUE TITLE
NOT WORKING

### ISSUE THREAD

**Issue by hasu-iihglobal** [DigitalCloud/nova-custom-views#12]
After installation try to npm run from the directory, I'm getting below error

`
ERROR in /var/www/html/meethugo/node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!/var/www/html/meethugo/vendor/laravel/nova/resources/js/views/Dashboard.vue
Module build failed: ReferenceError: Unknown plugin "transform-vue-jsx" specified in "/var/www/html/meethugo/vendor/laravel/nova/.babelrc" at 1, attempted to resolve relative to "/var/www/html/meethugo/vendor/laravel/nova"
    at /var/www/html/meethugo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/var/www/html/meethugo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/var/www/html/meethugo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/var/www/html/meethugo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/var/www/html/meethugo/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/var/www/html/meethugo/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/var/www/html/meethugo/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/var/www/html/meethugo/node_modules/babel-loader/lib/index.js:50:20)
    at /var/www/html/meethugo/node_modules/babel-loader/lib/fs-cache.js:118:18
    at ReadFileContext.callback (/var/www/html/meethugo/node_modules/babel-loader/lib/fs-cache.js:31:21)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:244:13)
 @ /var/www/html/meethugo/vendor/laravel/nova/resources/js/views/Dashboard.vue 4:21-403
 @ ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./resources/js/views/Dashboard.vue
 @ ./resources/js/views/Dashboard.vue
 @ ./resources/js/views.js
 @ multi ./resources/js/views.js ./resources/sass/views.scss
`

**Comment by devmtm** [comment]
please refer to #4 and #7.
